"use client";

import Link from "next/link";
import { useState } from "react";
import { CalendarDays, ChevronDown } from "lucide-react";

export default function CreatePersonalizedOfferPage() {
  const [formData, setFormData] = useState({ offerName: "", offerType: "", customer: "", discountType: "", validFrom: "", validTill: "", minimumBillAmount: "", offerDetails: "", status: "", product: "" });
  const updateField = (field: keyof typeof formData, value: string) => setFormData((data) => ({ ...data, [field]: value }));
  const handleSubmit = (event: React.FormEvent) => { event.preventDefault(); console.log("Personalized Offer Data:", formData); };
  const inputClass = "mt-1.5 w-full rounded-lg border border-gray-300 bg-white px-2 py-2.5 text-sm text-gray-700 outline-none placeholder:text-gray-400 focus:border-[#622581] focus:ring-2 focus:ring-[#622581]/20";
  const select = (field: keyof typeof formData, label: string, placeholder: string, options: string[]) => <label className="relative text-sm text-gray-800">{label}<select required value={formData[field]} onChange={(event) => updateField(field, event.target.value)} className={`${inputClass} appearance-none`}><option value="">{placeholder}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select><ChevronDown className="pointer-events-none absolute bottom-3 right-3 h-4 w-4 text-gray-400" /></label>;
  return (
    <div className="scrollbar-none min-h-full min-w-0 space-y-6 overflow-x-hidden overflow-y-auto font-nunito">
      <div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-poppins font-medium text-gray-800">Customer Management</h1><div className="mt-1 flex items-center gap-2 text-sm text-gray-500"><Link href="/admin/dashboard" className="hover:text-[#622581]">Admin</Link><span className="text-lg text-gray-400">›</span><span>Customer Management</span><span className="text-lg text-gray-400">›</span><span className="text-gray-800">Create Gift Card</span></div></div></div>
      <section className="min-h-[calc(100vh-190px)] border border-gray-100 bg-white"><div className="flex min-h-[calc(100vh-190px)] flex-col px-8 py-7"><h2 className="text-base font-poppins font-medium text-gray-800">Create Personalized Offers</h2><form onSubmit={handleSubmit} className="mt-5 flex flex-1 flex-col"><div className="grid grid-cols-1 gap-x-10 gap-y-3 md:grid-cols-2 lg:gap-x-20 xl:gap-x-36"><label className="text-sm text-gray-800">offer Name<input required placeholder="Enter program name" value={formData.offerName} onChange={(e) => updateField("offerName",e.target.value)} className={inputClass} /></label>{select("offerType","offer Type","Select",["Percentage","Fixed Amount"])}{select("customer","Customer","Select Customer",["All Customers","New Customers"])}{select("discountType","Discount Type","Select",["Percentage","Fixed Amount"])}<div className="grid grid-cols-2 gap-6"><label className="relative text-sm text-gray-800">Valid From<input required type="date" value={formData.validFrom} onChange={(e) => updateField("validFrom",e.target.value)} className={`${inputClass} pr-9`} /><CalendarDays className="pointer-events-none absolute bottom-3 right-3 h-4 w-4 text-gray-400" /></label><label className="relative text-sm text-gray-800">Valid Till<input required type="date" value={formData.validTill} onChange={(e) => updateField("validTill",e.target.value)} className={`${inputClass} pr-9`} /><CalendarDays className="pointer-events-none absolute bottom-3 right-3 h-4 w-4 text-gray-400" /></label></div><label className="text-sm text-gray-800">Minimum Bill Amount<input required placeholder="Enter minimum Bill Amount" value={formData.minimumBillAmount} onChange={(e) => updateField("minimumBillAmount",e.target.value)} className={inputClass} /></label><label className="text-sm text-gray-800">Offer Details<textarea required rows={3} placeholder="Enter redemption details..." value={formData.offerDetails} onChange={(e) => updateField("offerDetails",e.target.value)} className={`${inputClass} resize-none`} /></label>{select("status","Status","Select State",["Active","Inactive"])}{select("product","Product for Free (If Applicable)","Select Product",["Turmeric Powder","All Products"])}</div><div className="mt-auto flex justify-end pt-6"><button type="submit" className="min-w-[120px] rounded-lg bg-[#622581] px-8 py-2.5 font-poppins text-xl font-medium text-white hover:bg-[#52206d]">Submit</button></div></form></div></section>
    </div>
  );
}
